# Mistral Small 4

wandb:
  run_name: "mistral-small-2603"

metadata:
  release_date: "2026-03-16"
  size_category: null
  model_size: null
  context_window: 262000

model:
  name: mistralai/mistral-small-2603
  client: litellm
  provider: openrouter
  api_key_env: OPENROUTER_API_KEY

  params:
    max_tokens: 64000
    temperature: 1.0
    timeout: 7200
    max_retries: 5

benchmarks:
  bfcl:
    use_native_tools: false
    max_tokens: 64000
  swebench_verified_official_80:
    max_tokens: 64000
